### ISSUE TITLE
scotch recipe includes metis.h, conflicting with metis itself

### ISSUE THREAD

**Issue by minrk** [conda-forge/scotch-feedstock#24]
scotch installs a metis.h, which I think is meant as a fallback mechanism.

I propose moving this to `include/scotch/metis.h` or just removing it, so it's not conflicting with the 'real' metis package.

**Comment by minrk** [comment]
[Looking at debian](https://packages.debian.org/sid/libscotchmetis-dev), libscotchmetis is treated a different package. We could do that as well. I'm not sure if anyone is using scotchmetis, so maybe removing all of the scotchmetis remnants from here would be the right thing to do, since we have 'proper' metis packaged already, I'm not sure if there's a reason to use scotchmetis from conda-forge.

**Comment by dalcinl** [comment]
Yes, I would vote for removal as well. This would simplify my live in petsc, I could configure with both scotch and parmetis.

**Comment by minrk** [comment]
@dalcinl thansk! I ran into this precisely because I was doing an update to petsc to load hypre+mumps+superlu, and it's failing because scotch clobbered the real metis.h with its incomplete one here.
